import {TokenSwap} from '@apocentre/spl-token-swap'
export {CurveType} from '@apocentre/spl-token-swap'

export const createPair = async (
  connection,
  feePayer,
  tokenSwapAccount,
  authority,
  tokenAccountA,
  tokenAccountB,
  poolToken,
  mintA,
  mintB,
  feeAccount,
  tokenAccountPool,
  swapProgramId,
  tokenProgramId,
  tradeFeeNumerator,
  tradeFeeDenominator,
  ownerTradeFeeNumerator,
  ownerTradeFeeDenominator,
  ownerWithdrawFeeNumerator,
  ownerWithdrawFeeDenominator,
  hostFeeNumerator,
  hostFeeDenominator,
  curveType,
  curveParameters,
) => {
  await TokenSwap.createTokenSwap(
    connection,
    feePayer,
    tokenSwapAccount,
    authority,
    tokenAccountA,
    tokenAccountB,
    poolToken,
    mintA,
    mintB,
    feeAccount,
    tokenAccountPool,
    swapProgramId,
    tokenProgramId,
    tradeFeeNumerator,
    tradeFeeDenominator,
    ownerTradeFeeNumerator,
    ownerTradeFeeDenominator,
    ownerWithdrawFeeNumerator,
    ownerWithdrawFeeDenominator,
    hostFeeNumerator,
    hostFeeDenominator,
    curveType,
    curveParameters,
  )
}
